= Web Application
A web application has a frontend and a backend.
The frontend is served to the user in a web browser and communicates with the backend, which is hosted on a server, via a REST API.
Depending on the expected load generated by the frontend, the backend can be horizontally scaled, in which case that frontend communicates with the backend via a load balancer.

Pros:
- Frontend and backend can be written in completely different programming languages
- JavaScript has a wide range of libraries available for frontend development

Cons:
- JavaScript has a weak type-system
- The backend would have to organize VisualFP project files for multiple users on a server
